### ISSUE TITLE
SVCSUBNET_NAME and service-cidr

### ISSUE THREAD

**Issue by jemag** [kevingbb/ready-aks-security#5]
Perhaps I am misunderstanding something, but I thought that the subnet "SVCSUBNET_NAME" was created specifically for the kubernetes services, yet it does not seem to be used later on in the README procedure.

Should the cidr of that subnet (10.42.2.0/24) be used for the --service-cidr parameter instead of the one given in (10.41.0.0/16) ? : 
```
az aks create -g $RG -n $NAME -k 1.12.6 -l $LOC \
  --node-count 2 --generate-ssh-keys \
  --enable-addons monitoring \
  --workspace-resource-id $WORKSPACEIDURL \
  --network-plugin azure \
  --network-policy azure \
  --service-cidr 10.41.0.0/16 \
  --dns-service-ip 10.41.0.10 \
  --docker-bridge-address 172.17.0.1/16 \
  --vnet-subnet-id $SUBNETID \
  --service-principal $APPID \
  --client-secret $PASSWORD \
  --no-wait
```

**Comment by kevingbb** [comment]
Hi jemag, great question as there is typically a lot of confusion in this area. The service-cidr in the parameters should be non-routable per the documentation, https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#plan-ip-addressing-for-your-cluster.

The SVCSUBNET_NAME subnet is used for provisioning Internal Load Balancers (ILBs) to help with ingress traffic into the cluster/services. The reason it is separate is so that it does not take up an IP Address in the AKS subnet which is used for the Nodes and Pods. The separate subnet also allows us to assign a static IP from the service subnet for DNS for example. You will see that a static IP Address from that service subnet is used when provisioning the service for the web front-end.
